name: my_new_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  http: ^1.2.2
  mime: ^2.0.0
  http_parser: ^4.1.2
  shared_preferences: ^2.2.3
  firebase_core: ^4.11.0
  firebase_analytics: ^12.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/demo_food/

